<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="5" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performAdditionTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performAdditionTest.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performConcatenationTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performConcatenationTest.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performDivisionTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performDivisionTest.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performMultiplicationTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performMultiplicationTest.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performSubtractionTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performSubtractionTest.png' height='100' width='100'/> </a>]]>
    </line>
  </reporter-output>
  <suite started-at="2024-06-22T00:32:25 PST" name="Default suite" finished-at="2024-06-22T00:32:40 PST" duration-ms="15242">
    <groups>
    </groups>
    <test started-at="2024-06-22T00:32:25 PST" name="Default test" finished-at="2024-06-22T00:32:40 PST" duration-ms="15242">
      <class name="ian.project.testcases.CalculatorTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:18 PST" name="setUp" finished-at="2024-06-22T00:32:25 PST" duration-ms="7011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:25 PST" name="setupBeforeTest" finished-at="2024-06-22T00:32:25 PST" duration-ms="242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method signature="performAdditionTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:25 PST" name="performAdditionTest" finished-at="2024-06-22T00:32:26 PST" duration-ms="597" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [25] but found [15]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [25] but found [15]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ian.project.testcases.CalculatorTests.performAdditionTest(CalculatorTests.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performAdditionTest -->
        <test-method is-config="true" signature="captureTest(org.testng.ITestResult)[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:26 PST" name="captureTest" finished-at="2024-06-22T00:32:28 PST" duration-ms="2165" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=performAdditionTest status=FAILURE method=CalculatorTests.performAdditionTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performAdditionTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performAdditionTest.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- captureTest -->
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:28 PST" name="setupBeforeTest" finished-at="2024-06-22T00:32:28 PST" duration-ms="251" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method signature="performConcatenationTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:28 PST" name="performConcatenationTest" finished-at="2024-06-22T00:32:29 PST" duration-ms="652" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1015] but found [15]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1015] but found [15]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ian.project.testcases.CalculatorTests.performConcatenationTest(CalculatorTests.java:111)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performConcatenationTest -->
        <test-method is-config="true" signature="captureTest(org.testng.ITestResult)[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:29 PST" name="captureTest" finished-at="2024-06-22T00:32:31 PST" duration-ms="2150" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=performConcatenationTest status=FAILURE method=CalculatorTests.performConcatenationTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performConcatenationTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performConcatenationTest.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- captureTest -->
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:31 PST" name="setupBeforeTest" finished-at="2024-06-22T00:32:31 PST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method signature="performDivisionTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:31 PST" name="performDivisionTest" finished-at="2024-06-22T00:32:32 PST" duration-ms="894" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0.6666666666666666] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0.6666666666666666] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ian.project.testcases.CalculatorTests.performDivisionTest(CalculatorTests.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performDivisionTest -->
        <test-method is-config="true" signature="captureTest(org.testng.ITestResult)[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:32 PST" name="captureTest" finished-at="2024-06-22T00:32:34 PST" duration-ms="2185" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=performDivisionTest status=FAILURE method=CalculatorTests.performDivisionTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performDivisionTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performDivisionTest.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- captureTest -->
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:34 PST" name="setupBeforeTest" finished-at="2024-06-22T00:32:34 PST" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method signature="performMultiplicationTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:34 PST" name="performMultiplicationTest" finished-at="2024-06-22T00:32:35 PST" duration-ms="650" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [150] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [150] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ian.project.testcases.CalculatorTests.performMultiplicationTest(CalculatorTests.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performMultiplicationTest -->
        <test-method is-config="true" signature="captureTest(org.testng.ITestResult)[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:35 PST" name="captureTest" finished-at="2024-06-22T00:32:37 PST" duration-ms="2134" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=performMultiplicationTest status=FAILURE method=CalculatorTests.performMultiplicationTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performMultiplicationTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performMultiplicationTest.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- captureTest -->
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:37 PST" name="setupBeforeTest" finished-at="2024-06-22T00:32:37 PST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method signature="performSubtractionTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:37 PST" name="performSubtractionTest" finished-at="2024-06-22T00:32:38 PST" duration-ms="601" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-5] but found [-15]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-5] but found [-15]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ian.project.testcases.CalculatorTests.performSubtractionTest(CalculatorTests.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performSubtractionTest -->
        <test-method is-config="true" signature="captureTest(org.testng.ITestResult)[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:38 PST" name="captureTest" finished-at="2024-06-22T00:32:40 PST" duration-ms="2126" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=performSubtractionTest status=FAILURE method=CalculatorTests.performSubtractionTest()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performSubtractionTest.png'> <img src='C:\Users\User\Documents\GitHub\rcgchallenge\test-output\screenshots\Report_22_06_2024_12_32_25_BUILD-7\performSubtractionTest.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- captureTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ian.project.testcases.CalculatorTests@5d0a1059]" started-at="2024-06-22T00:32:40 PST" name="tearDown" finished-at="2024-06-22T00:32:40 PST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ian.project.testcases.CalculatorTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
